[package]
name = "sashimi"
version = "0.0.1"
description = "Simplistic, lightweight encryption."
edition = "2021"

[dependencies]
rpassword = "6.0.1"
sha3 = "0.10.1"
aes-gcm = "0.9.4"

[build-dependencies]
chrono = "0.4.19"