[package]
name = "sashimi"
version = "0.0.1"
description = "Simplistic, lightweight encryption."
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
rpassword = "6.0.1"
sha3 = "0.10.1"
aes = "0.8.1"
zip = "0.6.0"

[build-dependencies]
chrono = "0.4.19"